# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# Terragrunt Generated Provider Block
terraform {
  required_version = ">= 0.13"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "5.31.1"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "~> 5.31.1"
    }
    github = {
      source  = "integrations/github"
      version = "~> 5.0"
    }
  }
}

provider "google" {
  project = "ranor-suite"
  region  = "us-central1"
}

provider "github" {
    owner  = "ranson21"
}
